minVersion: '0.23.1'
changelogPolicy: simple
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: aws-lambda-layer
    includeNames: /^sentry-node-serverless-\d+.\d+.\d+(-(beta|alpha)\.\d+)?\.zip$/
    layerName: SentryNodeServerlessSDK
    compatibleRuntimes:
      - name: node
        versions:
          - nodejs10.x
          - nodejs12.x
          - nodejs14.x
    license: MIT
  - name: gcs
    includeNames: /.*\.js.*$/
    bucket: sentry-js-sdk
    paths:
      - path: /{{version}}/
        metadata:
          cacheControl: 'public, max-age=31536000'
  - name: github
    includeNames: /^sentry-.*$/
  - name: npm
  - name: registry
    sdks:
      'npm:@sentry/browser':
        onlyIfPresent: /^sentry-browser-.*\.tgz$/
        includeNames: /\.js$/
        checksums:
          - algorithm: sha384
            format: base64
      'npm:@sentry/node':
        onlyIfPresent: /^sentry-node-.*\.tgz$/
      'npm:@sentry/react':
        onlyIfPresent: /^sentry-react-.*\.tgz$/
      'npm:@sentry/vue':
        onlyIfPresent: /^sentry-vue-.*\.tgz$/
      'npm:@sentry/gatsby':
        onlyIfPresent: /^sentry-gatsby-.*\.tgz$/
      'npm:@sentry/angular':
        onlyIfPresent: /^sentry-angular-.*\.tgz$/
      'npm:@sentry/wasm':
        onlyIfPresent: /^sentry-wasm-.*\.tgz$/
      'npm:@sentry/nextjs':
        onlyIfPresent: /^sentry-nextjs-.*\.tgz$/
